### ISSUE TITLE
strange: SpCodePresenter>>#doBrowseImplementors reverted to old version

### ISSUE THREAD

**Issue by MarcusDenker** [pharo-spec/Spec#1176] opened 2021-10-18 14:47 UTC
We changed SpCodePresenter>>#doBrowseImplementors in #1150, but the current version in Pharo10 still have the (bad) code
that calls #browseImplementorOfPoolVar

**Comment by MarcusDenker** [comment] 2021-10-18 14:55
The method #browseSelectedSelectorIfGlobal:ifNotGlobal: was changed by #1153, but that change is not visible in Pharo10 (it has the old code)

**Comment by estebanlm** [comment] 2021-10-18 19:27
this was reverted by @guillep here: https://github.com/pharo-spec/Spec/pull/1153

no idea if this was an explicit revert or a mistake... Guille?

**Comment by guillep** [comment] 2021-10-18 19:35
I need more context. @MarcusDenker says the right change is in #1153, @estebanlm that it was reverted in #1153.

:)

**Comment by guillep** [comment] 2021-10-19 08:18
Ok, so, the thing is:

Pharo 10 image has the following code which apparently is an old version:

```smalltalk
doBrowseImplementors
	| result selectionIsPoolVar |

	selectionIsPoolVar := self browseImplementorOfPoolVar.
	selectionIsPoolVar ifTrue: [ ^ self ].
	 
	result := self
		browseSelectedSelectorIfGlobal: [ :global | global browse ]
		ifNotGlobal: [ :selector | self systemNavigation browseAllImplementorsOf: selector ].
	result ifNil: [ self application inform: 'No selectors found.' ]
```

We checked with @MarcusDenker and that is the version that is in the latest Spec commit. So that's ok.
Now, the question is, where did that change get lost?

Issue #1153 did not touch method `browseImplementorOfPoolVar` nor any of its users.

**Comment by guillep** [comment] 2021-10-19 08:20
The code we would like to have there, is in this PR, which was merged, but that code is not there in the history.

https://github.com/pharo-spec/Spec/pull/1150/files

Weird.

**Comment by estebanlm** [comment] 2021-10-19 08:22
yes, method history (in image) shows it is reverted in your PR... weird. Maybe an iceberg bug?

**Comment by guillep** [comment] 2021-10-19 08:24
Even more weird, doing a blame gives us:

![image](https://user-images.githubusercontent.com/708322/137871820-b6200c15-5bf5-40d4-b4d4-d57a03c89999.png)

But Marcus' changes were AFTER that. It's like his changes were not even integrated. (or we broke `git blame`, which I don't think :P)

**Comment by guillep** [comment] 2021-10-19 08:30
And my code from #1153 is not there either. That got lost.

![image](https://user-images.githubusercontent.com/708322/137872868-3d098fcc-dcaa-483c-a2af-c0ab98f34c34.png)

**Comment by guillep** [comment] 2021-10-19 08:32
Looks like my change was merged. In branch dev-1.0.

That could be the cause of all this.

![image](https://user-images.githubusercontent.com/708322/137873311-f0fa56f2-40fb-4d03-993c-0d7094f05328.png)

**Comment by estebanlm** [comment] 2021-10-19 08:42
I regularly change the base to merge in my thing several stuff (and make sure the tests pass after the merge)

**Comment by guillep** [comment] 2021-10-19 08:43
Ok, so my changes are not yet in the Pharo 10 branch, that explains why my changes are not visible into the image. So that's ok.

Now, for Marcus' changes, we have tracked down the problem to this sequence of commits:

![image](https://user-images.githubusercontent.com/708322/137874617-9137853f-e90b-4027-8330-621ff721d068.png)

When Marcus' changes were merged in commit 13a8fbcccb0cdb73402e963d4f5dd95022b6ab96, the repository had both of Marcus' versions. However, in the next "merge dev-1.0 into Pharo10" (e4e34673bc10c7749bbfa664954f49fe750c8a6e) that change got lost. I think it is related to the order in which things were merged/backported from the pharo9 branch into dev-1.0 branch. Notice that Arturo's original PR was against Pharo 9

**Comment by guillep** [comment] 2021-10-19 08:45
Even funnier:

The merge commit is introducing only one of both changes from marcus:

https://github.com/pharo-spec/Spec/commit/0c127f258720739e6a43329cf52c573686955e69

**Comment by estebanlm** [comment] 2021-10-19 08:47
but I do not have it in my image (with dev-1.0) either.

**Comment by guillep** [comment] 2021-10-19 08:48
I think this was just a bad conflict resolution: Marcus touched a change you formatted at the same time. But only one of those got through.

I think we should just "re-merge" Marcus code and we can forget about this.

**Closed as completed** 2021-10-22 09:22 UTC
